# Base Python image
FROM python:3.12-slim

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Copy requirements file
COPY requirements.txt .

# Install packages using pip
RUN pip install --no-cache-dir -r requirements.txt

